/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package commanders.of.jogoddar;

import commanders.of.jogoddar.classes.Carta;
import commanders.of.jogoddar.classes.Jogador;
import commanders.of.jogoddar.classes.Personagem;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author natha
 */
public class Battle extends javax.swing.JFrame {

    /**
     * Creates new form Battle
     */
    private boolean jogo = true;
    private int cont = 0;
    private int turno;
    private ArrayList<Carta> baralho = new ArrayList<Carta>();
    private ArrayList<Jogador> jg = new ArrayList<Jogador>();
    public Battle(Jogador Jogador1,Jogador Jogador2,Jogador Jogador3,Jogador Jogador4) {
        jg.add(Jogador1);
        jg.add(Jogador2);
        jg.add(Jogador3);
        jg.add(Jogador4);
        initComponents();
        ordenarJogadores();
        
    }

    private Battle() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personagem2 = new javax.swing.JLabel();
        vida3 = new javax.swing.JLabel();
        Personagem3 = new javax.swing.JLabel();
        vida1 = new javax.swing.JLabel();
        Carta2 = new javax.swing.JLabel();
        Personagem1 = new javax.swing.JLabel();
        Carta3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Vidaatual = new javax.swing.JLabel();
        Atual = new javax.swing.JLabel();
        vida2 = new javax.swing.JLabel();
        Carta1 = new javax.swing.JLabel();
        cartagigante = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        personagem2.setText("jLabel7");
        getContentPane().add(personagem2);
        personagem2.setBounds(1630, 0, 290, 280);

        vida3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vida3.setForeground(new java.awt.Color(255, 255, 255));
        vida3.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\img\\vidamaispequena.png")); // NOI18N
        vida3.setText("20");
        vida3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(vida3);
        vida3.setBounds(1680, 810, 60, 120);

        Personagem3.setText("jLabel7");
        getContentPane().add(Personagem3);
        Personagem3.setBounds(1730, 700, 190, 280);

        vida1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vida1.setForeground(new java.awt.Color(255, 255, 255));
        vida1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\img\\vidamaispequena.png")); // NOI18N
        vida1.setText("20");
        vida1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(vida1);
        vida1.setBounds(290, 10, 60, 120);

        Carta2.setForeground(new java.awt.Color(255, 255, 255));
        Carta2.setText("jLabel4");
        getContentPane().add(Carta2);
        Carta2.setBounds(880, 830, 110, 140);

        Personagem1.setText("jLabel7");
        getContentPane().add(Personagem1);
        Personagem1.setBounds(10, 0, 240, 280);

        Carta3.setBackground(new java.awt.Color(255, 255, 255));
        Carta3.setForeground(new java.awt.Color(255, 255, 255));
        Carta3.setText("jLabel4");
        getContentPane().add(Carta3);
        Carta3.setBounds(1030, 830, 110, 140);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Turno:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(490, 0, 340, 150);

        Vidaatual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Vidaatual.setForeground(new java.awt.Color(255, 255, 255));
        Vidaatual.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\img\\vidamaispequena.png")); // NOI18N
        Vidaatual.setText("20");
        Vidaatual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Vidaatual);
        Vidaatual.setBounds(440, 790, 60, 120);

        Atual.setName("Atual"); // NOI18N
        getContentPane().add(Atual);
        Atual.setBounds(500, 680, 240, 300);

        vida2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vida2.setForeground(new java.awt.Color(255, 255, 255));
        vida2.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\img\\vidamaispequena.png")); // NOI18N
        vida2.setText("20");
        vida2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(vida2);
        vida2.setBounds(1510, 40, 60, 120);

        Carta1.setBackground(new java.awt.Color(255, 255, 255));
        Carta1.setForeground(new java.awt.Color(255, 255, 255));
        Carta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Carta1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Carta1MouseExited(evt);
            }
        });
        getContentPane().add(Carta1);
        Carta1.setBounds(740, 830, 110, 140);

        cartagigante.setText("jLabel2");
        getContentPane().add(cartagigante);
        cartagigante.setBounds(630, 130, 500, 600);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Passar turno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 890, 120, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\img\\colosseum_121736920.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1940, 1200);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void passarVez(){
        turno++;
        if(turno > 3 ){
            turno = 0;
            cont+=1;
        }
    }
    //metodo para mostrar os dados de cada personagem na interface grafica
    private void rodartabuleiro(){
        switch(turno){
            case 0:
                ImageIcon avatar00 = new ImageIcon(jg.get(0).getpersonagem().geticon());
                Atual.setIcon(avatar00);
                Vidaatual.setText(Integer.toString(jg.get(0).getVida()));
                /*ImageIcon carta00 = new ImageIcon(jg.get(0).getMao().get(0).getimagem());
                ImageIcon carta01 = new ImageIcon(jg.get(0).getMao().get(1).getimagem());
                ImageIcon carta02 = new ImageIcon(jg.get(0).getMao().get(2).getimagem());
                Carta1.setIcon(carta00);
                Carta2.setIcon(carta01);
                Carta3.setIcon(carta02);*/
                ImageIcon avatar01 = new ImageIcon(jg.get(1).getpersonagem().geticon());
                Personagem1.setIcon(avatar01);
                vida1.setText(Integer.toString(jg.get(1).getVida()));
                
                ImageIcon avatar02 = new ImageIcon(jg.get(2).getpersonagem().geticon());
                personagem2.setIcon(avatar02);
                vida2.setText(Integer.toString(jg.get(2).getVida()));
                
                ImageIcon avatar03 = new ImageIcon(jg.get(3).getpersonagem().geticon());
                Personagem3.setIcon(avatar03);
                vida3.setText(Integer.toString(jg.get(3).getVida()));
                break;
            case 1:
                /*ImageIcon carta10 = new ImageIcon(jg.get(0).getMao().get(0).getimagem());
                ImageIcon carta11 = new ImageIcon(jg.get(0).getMao().get(1).getimagem());
                ImageIcon carta12 = new ImageIcon(jg.get(0).getMao().get(2).getimagem());
                Carta1.setIcon(carta10);
                Carta2.setIcon(carta11);
                Carta3.setIcon(carta12);*/
                ImageIcon avatar10 = new ImageIcon(jg.get(1).getpersonagem().geticon());
                Atual.setIcon(avatar10);
                Vidaatual.setText(Integer.toString(jg.get(1).getVida()));
                
                ImageIcon avatar11 = new ImageIcon(jg.get(2).getpersonagem().geticon());
                Personagem1.setIcon(avatar11);
                vida1.setText(Integer.toString(jg.get(2).getVida()));
                
                ImageIcon avatar12 = new ImageIcon(jg.get(3).getpersonagem().geticon());
                personagem2.setIcon(avatar12);
                vida2.setText(Integer.toString(jg.get(3).getVida()));
                
                ImageIcon avatar13 = new ImageIcon(jg.get(0).getpersonagem().geticon());
                Personagem3.setIcon(avatar13);
                vida3.setText(Integer.toString(jg.get(0).getVida()));
                break;
            case 2:
              /*  ImageIcon carta20 = new ImageIcon(jg.get(0).getMao().get(0).getimagem());
                ImageIcon carta21 = new ImageIcon(jg.get(0).getMao().get(1).getimagem());
                ImageIcon carta22 = new ImageIcon(jg.get(0).getMao().get(2).getimagem());
                Carta1.setIcon(carta20);
                Carta2.setIcon(carta21);
                Carta3.setIcon(carta22);*/
                ImageIcon avatar20 = new ImageIcon(jg.get(2).getpersonagem().geticon());
                Atual.setIcon(avatar20);
                Vidaatual.setText(Integer.toString(jg.get(2).getVida()));
                
                ImageIcon avatar21 = new ImageIcon(jg.get(3).getpersonagem().geticon());
                Personagem1.setIcon(avatar21);
                vida1.setText(Integer.toString(jg.get(3).getVida()));
                
                ImageIcon avatar22 = new ImageIcon(jg.get(0).getpersonagem().geticon());
                personagem2.setIcon(avatar22);
                vida2.setText(Integer.toString(jg.get(0).getVida()));
                
                ImageIcon avatar23 = new ImageIcon(jg.get(1).getpersonagem().geticon());
                Personagem3.setIcon(avatar23);
                vida3.setText(Integer.toString(jg.get(1).getVida()));
                break;
            case 3:
                /*ImageIcon carta30 = new ImageIcon(jg.get(0).getMao().get(0).getimagem());
                ImageIcon carta31 = new ImageIcon(jg.get(0).getMao().get(1).getimagem());
                ImageIcon carta32 = new ImageIcon(jg.get(0).getMao().get(2).getimagem());
                Carta1.setIcon(carta30);
                Carta2.setIcon(carta31);
                Carta3.setIcon(carta32);*/
                ImageIcon avatar30 = new ImageIcon(jg.get(3).getpersonagem().geticon());
                Atual.setIcon(avatar30);
                Vidaatual.setText(Integer.toString(jg.get(3).getVida()));
                
                ImageIcon avatar31 = new ImageIcon(jg.get(0).getpersonagem().geticon());
                Personagem1.setIcon(avatar31);
                vida1.setText(Integer.toString(jg.get(0).getVida()));
                
                ImageIcon avatar32 = new ImageIcon(jg.get(1).getpersonagem().geticon());
                personagem2.setIcon(avatar32);
                vida2.setText(Integer.toString(jg.get(1).getVida()));
                
                ImageIcon avatar33 = new ImageIcon(jg.get(2).getpersonagem().geticon());
                Personagem3.setIcon(avatar33);
                vida3.setText(Integer.toString(jg.get(2).getVida()));
        }
    }
    public  void embaralhar(){
        Collections.shuffle(baralho);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        passarVez();
        rodartabuleiro();
        
        jLabel13.setText("Turno:"+this.cont);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Carta1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta1MouseEntered
       cartagigante.setIcon(Carta1.getIcon());
    }//GEN-LAST:event_Carta1MouseEntered

    private void Carta1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta1MouseExited
       cartagigante.setIcon(null);
    }//GEN-LAST:event_Carta1MouseExited

    private void Carta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta1MouseClicked
       String[] jog = new String[4];
       Jogador jogadorescolhido;
       
        for(int i=0;i<4;i++){
            jog[i] = jg.get(i).getNome();
        
        }
       String selecionado = (String)JOptionPane.showInputDialog(null,"Selecione o Alvo","",JOptionPane.QUESTION_MESSAGE,null,jog,jog[0]);
       for(Jogador jogador : jg ){
           if(jogador.getNome() == selecionado){
               jogadorescolhido = jogador;
           }
       }
       jg.get(this.turno).usarCarta(jg.get(this.turno).getMao().get(0));
    }//GEN-LAST:event_Carta1MouseClicked
    
    private void ordenarJogadores(){
        Random primeiro = new Random();
        turno = primeiro.nextInt(4);

       JOptionPane.showMessageDialog(null,"Primeiro a jogar é o " + jg.get(turno).getNome());
       rodartabuleiro();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Battle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atual;
    private javax.swing.JLabel Carta1;
    private javax.swing.JLabel Carta2;
    private javax.swing.JLabel Carta3;
    private javax.swing.JLabel Personagem1;
    private javax.swing.JLabel Personagem3;
    private javax.swing.JLabel Vidaatual;
    private javax.swing.JLabel cartagigante;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel personagem2;
    private javax.swing.JLabel vida1;
    private javax.swing.JLabel vida2;
    private javax.swing.JLabel vida3;
    // End of variables declaration//GEN-END:variables
}
