/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package commanders.of.jogoddar;

import commanders.of.jogoddar.classes.Buff;
import commanders.of.jogoddar.classes.Carta;
import commanders.of.jogoddar.classes.Jogador;
import commanders.of.jogoddar.classes.Magia;
import commanders.of.jogoddar.classes.Musica;
import commanders.of.jogoddar.classes.Personagem;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author natha
 */
public class Battle extends javax.swing.JFrame {

    /**
     * Creates new form Battle
     */
    private boolean jogo = true;
    private int cont = 0;
    private int turno;
    private ArrayList<Carta> baralho = new ArrayList<Carta>();
    private static ArrayList<Jogador> jogadores = new ArrayList<Jogador>();
    private Musica trilha = new Musica("musicas\\\\batalha.wav");
    private Musica socar = new Musica("musicas\\\\soco.wav");
    private ArrayList<JLabel> visualCartas = new ArrayList<JLabel>(); 
     
    
    public void embaralhar(){
        Collections.shuffle(baralho);
    }
    

    public Battle(Jogador Jogador1,Jogador Jogador2,Jogador Jogador3,Jogador Jogador4) {
        
        for(int i=0;i<60;i++){
        baralho.add(new Buff("A grande guerra",2,3,"icons\\\\carta.png","icons\\\\miniatura.png","musicas\\\\cura.wav"));
        }
        
        embaralhar();
        visualCartas.add(Carta1);
        visualCartas.add(Carta2);
        visualCartas.add(Carta3);
            
        jogadores.add(Jogador1);
        jogadores.add(Jogador2);
        jogadores.add(Jogador3);
        jogadores.add(Jogador4);
         for(int i = 0; i < 4; i++){
            jogadores.get(i).comprarCarta(baralho);
            jogadores.get(i).comprarCarta(baralho);
            jogadores.get(i).comprarCarta(baralho);

        }
        initComponents();
        trilha.iniciarmusica();
        ordenarJogadores();
        checarcarta(this.turno);
        
    }

    private Battle() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personagem2 = new javax.swing.JLabel();
        vida3 = new javax.swing.JLabel();
        Personagem3 = new javax.swing.JLabel();
        vida1 = new javax.swing.JLabel();
        Carta2 = new javax.swing.JLabel();
        Personagem1 = new javax.swing.JLabel();
        Carta3 = new javax.swing.JLabel();
        Vezde = new javax.swing.JLabel();
        Vidaatual = new javax.swing.JLabel();
        Atual = new javax.swing.JLabel();
        vida2 = new javax.swing.JLabel();
        Carta1 = new javax.swing.JLabel();
        cartagigante = new javax.swing.JLabel();
        Soco = new javax.swing.JLabel();
        contadordeturno = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(personagem2);
        personagem2.setBounds(1630, 0, 290, 280);

        vida3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vida3.setForeground(new java.awt.Color(255, 255, 255));
        vida3.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\img\\vidamaispequena.png")); // NOI18N
        vida3.setText("20");
        vida3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(vida3);
        vida3.setBounds(1680, 810, 60, 120);

        Personagem3.setText("jLabel7");
        getContentPane().add(Personagem3);
        Personagem3.setBounds(1730, 700, 190, 280);

        vida1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vida1.setForeground(new java.awt.Color(255, 255, 255));
        vida1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\img\\vidamaispequena.png")); // NOI18N
        vida1.setText("20");
        vida1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(vida1);
        vida1.setBounds(290, 10, 60, 120);

        Carta2.setForeground(new java.awt.Color(255, 255, 255));
        Carta2.setText("jLabel4");
        Carta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Carta2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Carta2MouseExited(evt);
            }
        });
        getContentPane().add(Carta2);
        Carta2.setBounds(850, 830, 110, 140);
        getContentPane().add(Personagem1);
        Personagem1.setBounds(10, 0, 240, 280);

        Carta3.setBackground(new java.awt.Color(255, 255, 255));
        Carta3.setForeground(new java.awt.Color(255, 255, 255));
        Carta3.setText("jLabel4");
        Carta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Carta3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Carta3MouseExited(evt);
            }
        });
        getContentPane().add(Carta3);
        Carta3.setBounds(1030, 840, 110, 140);

        Vezde.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Vezde.setForeground(new java.awt.Color(255, 255, 255));
        Vezde.setText("Vez de:");
        getContentPane().add(Vezde);
        Vezde.setBounds(990, 0, 340, 150);

        Vidaatual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Vidaatual.setForeground(new java.awt.Color(255, 255, 255));
        Vidaatual.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\img\\vidamaispequena.png")); // NOI18N
        Vidaatual.setText("20");
        Vidaatual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Vidaatual);
        Vidaatual.setBounds(170, 850, 60, 120);

        Atual.setName("Atual"); // NOI18N
        getContentPane().add(Atual);
        Atual.setBounds(230, 670, 240, 300);

        vida2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vida2.setForeground(new java.awt.Color(255, 255, 255));
        vida2.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\img\\vidamaispequena.png")); // NOI18N
        vida2.setText("20");
        vida2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(vida2);
        vida2.setBounds(1510, 40, 60, 120);

        Carta1.setBackground(new java.awt.Color(255, 255, 255));
        Carta1.setForeground(new java.awt.Color(255, 255, 255));
        Carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanders/of/jogoddar/miniatura.png"))); // NOI18N
        Carta1.setToolTipText("");
        Carta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Carta1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Carta1MouseExited(evt);
            }
        });
        getContentPane().add(Carta1);
        Carta1.setBounds(670, 830, 110, 140);
        getContentPane().add(cartagigante);
        cartagigante.setBounds(630, 130, 500, 600);

        Soco.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\Commanders of Jogoddar\\icons\\fists.png")); // NOI18N
        Soco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SocoMouseClicked(evt);
            }
        });
        getContentPane().add(Soco);
        Soco.setBounds(-30, 800, 150, 90);

        contadordeturno.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        contadordeturno.setForeground(new java.awt.Color(255, 255, 255));
        contadordeturno.setText("Turno:");
        getContentPane().add(contadordeturno);
        contadordeturno.setBounds(490, 0, 340, 150);

        fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\img\\colosseum_121736920.jpg")); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 1940, 1200);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
   
    private void passarVez(){
        turno++;
        if(turno > 3 ){
            turno = 0;
            cont+=1;
        }
         contadordeturno.setText("Turno:"+this.cont);
         Vezde.setText("Vez de:"+jogadores.get(this.turno).getNome());
         jogadores.get(this.turno).checarBuff();
         jogadores.get(this.turno).checaDurabilidade();
         rodartabuleiro();
         checarcarta(turno);
         
    }
     
    private void checarcarta(int turno){
       /*for(int i = 0;i<jogadores.get(turno).getMao().size();i++){
          visualCartas.get(i).setIcon(new ImageIcon("miniatura.png"));
         //jogadores.get(turno).getMao().get(i).getimagem()
       }*/
       int i = 0;
        for (Carta carta : jogadores.get(turno).getMao()){
        visualCartas.get(i).setIcon(jogadores.get(turno).getMao().get(i).getimagem());
        i++;
        }

    }
    //metodo para mostrar os dados de cada personagem na interface grafica
    private void rodartabuleiro(){
        switch(turno){
            case 0:
                ImageIcon avatar00 = new ImageIcon(jogadores.get(0).getpersonagem().geticon());
                Atual.setIcon(avatar00);
                Vidaatual.setText(Integer.toString(jogadores.get(0).getVida()));
                ImageIcon avatar01 = new ImageIcon(jogadores.get(1).getpersonagem().geticon());
                Personagem1.setIcon(avatar01);
                vida1.setText(Integer.toString(jogadores.get(1).getVida()));
                
                ImageIcon avatar02 = new ImageIcon(jogadores.get(2).getpersonagem().geticon());
                personagem2.setIcon(avatar02);
                vida2.setText(Integer.toString(jogadores.get(2).getVida()));
                
                ImageIcon avatar03 = new ImageIcon(jogadores.get(3).getpersonagem().geticon());
                Personagem3.setIcon(avatar03);
                vida3.setText(Integer.toString(jogadores.get(3).getVida()));
                
                
                break;
            case 1:
                
                //Carta1.setIcon(carta10);
                //Carta2.setIcon(carta11);
                //Carta3.setIcon(carta12);
                
                ImageIcon avatar10 = new ImageIcon(jogadores.get(1).getpersonagem().geticon());
                Atual.setIcon(avatar10);
                Vidaatual.setText(Integer.toString(jogadores.get(1).getVida()));
                ImageIcon avatar11 = new ImageIcon(jogadores.get(2).getpersonagem().geticon());
                Personagem1.setIcon(avatar11);
                vida1.setText(Integer.toString(jogadores.get(2).getVida()));
                
                ImageIcon avatar12 = new ImageIcon(jogadores.get(3).getpersonagem().geticon());
                personagem2.setIcon(avatar12);
                vida2.setText(Integer.toString(jogadores.get(3).getVida()));
                
                ImageIcon avatar13 = new ImageIcon(jogadores.get(0).getpersonagem().geticon());
                Personagem3.setIcon(avatar13);
                vida3.setText(Integer.toString(jogadores.get(0).getVida()));
              
                break;
            case 2:
                
                //Carta1.setIcon(carta20);
                //Carta2.setIcon(carta21);
                //Carta3.setIcon(carta22);
                
                ImageIcon avatar20 = new ImageIcon(jogadores.get(2).getpersonagem().geticon());
                Atual.setIcon(avatar20);
                Vidaatual.setText(Integer.toString(jogadores.get(2).getVida()));
                
                ImageIcon avatar21 = new ImageIcon(jogadores.get(3).getpersonagem().geticon());
                Personagem1.setIcon(avatar21);
                vida1.setText(Integer.toString(jogadores.get(3).getVida()));
                
                ImageIcon avatar22 = new ImageIcon(jogadores.get(0).getpersonagem().geticon());
                personagem2.setIcon(avatar22);
                vida2.setText(Integer.toString(jogadores.get(0).getVida()));
                ImageIcon avatar23 = new ImageIcon(jogadores.get(1).getpersonagem().geticon());
                Personagem3.setIcon(avatar23);
                vida3.setText(Integer.toString(jogadores.get(1).getVida()));
                break;
            case 3:
               
                //Carta1.setIcon(carta30);
                //Carta2.setIcon(carta31);
                //Carta3.setIcon(carta32);
                
                ImageIcon avatar30 = new ImageIcon(jogadores.get(3).getpersonagem().geticon());
                Atual.setIcon(avatar30);
                Vidaatual.setText(Integer.toString(jogadores.get(3).getVida()));
                
                ImageIcon avatar31 = new ImageIcon(jogadores.get(0).getpersonagem().geticon());
                Personagem1.setIcon(avatar31);
                vida1.setText(Integer.toString(jogadores.get(0).getVida()));
                
                ImageIcon avatar32 = new ImageIcon(jogadores.get(1).getpersonagem().geticon());
                personagem2.setIcon(avatar32);
                vida2.setText(Integer.toString(jogadores.get(1).getVida()));
                ImageIcon avatar33 = new ImageIcon(jogadores.get(2).getpersonagem().geticon());
                Personagem3.setIcon(avatar33);
                vida3.setText(Integer.toString(jogadores.get(2).getVida()));
        }
    }
    public static final ArrayList<Jogador> getjogadores(){
        return jogadores;
    }
    private void Carta1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta1MouseEntered
       cartagigante.setIcon(Carta1.getIcon());
    }//GEN-LAST:event_Carta1MouseEntered

    private void Carta1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta1MouseExited
       cartagigante.setIcon(null);
    }//GEN-LAST:event_Carta1MouseExited

    private void Carta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta1MouseClicked
        if(jogadores.get(this.turno).verificarindex(0)==true){
            int dialog = JOptionPane.YES_NO_OPTION;
                JOptionPane.showConfirmDialog (null, "Deseja usar a carta ?","Carta", dialog);
            if(dialog == JOptionPane.YES_OPTION){
                jogadores.get(this.turno).usarCarta(jogadores.get(this.turno).getMao().get(0));
                
                Carta1.setIcon(null);
                Carta1.setText("");
                Carta1.setEnabled(false);
                passarVez();
            }    
        }
    }//GEN-LAST:event_Carta1MouseClicked

    private void Carta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta2MouseClicked
        if(jogadores.get(this.turno).verificarindex(1)==true){
            int dialog = JOptionPane.YES_NO_OPTION;
                JOptionPane.showConfirmDialog (null, "Deseja usar a carta ?","Carta", dialog);
            if(dialog == JOptionPane.YES_OPTION){
                jogadores.get(this.turno).usarCarta(jogadores.get(this.turno).getMao().get(1));
                
                Carta2.setIcon(null);
                Carta2.setText("");
                Carta2.setEnabled(false);
            }    
        }
      
    }//GEN-LAST:event_Carta2MouseClicked

    private void SocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SocoMouseClicked
      String[] posicaoalvos = new String[4];
       for(int i=0; i<4;i++){
           posicaoalvos[i] = jogadores.get(i).getNome();
       }
         int n = JOptionPane.showOptionDialog(null, "Escolha o jogador alvo",
                "Escolha o alvo",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, posicaoalvos, posicaoalvos[0]);
         jogadores.get(this.turno).socar(jogadores.get(n));
         socar.iniciarmusica();
         passarVez();         
    }//GEN-LAST:event_SocoMouseClicked

    private void Carta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta3MouseClicked
        if(jogadores.get(this.turno).verificarindex(2) == true){
            int dialog = JOptionPane.YES_NO_OPTION;
                JOptionPane.showConfirmDialog (null, "Deseja usar a carta ?","Carta", dialog);
            if(dialog == JOptionPane.YES_OPTION){
                jogadores.get(this.turno).usarCarta(jogadores.get(this.turno).getMao().get(2));
                Carta3.setIcon(null);
                Carta3.setEnabled(false);
                Carta3.setText("");

            }    
        }
    }//GEN-LAST:event_Carta3MouseClicked

    private void Carta2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta2MouseEntered
       cartagigante.setIcon(Carta2.getIcon());

    }//GEN-LAST:event_Carta2MouseEntered

    private void Carta2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta2MouseExited
        cartagigante.setIcon(null);
    }//GEN-LAST:event_Carta2MouseExited

    private void Carta3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta3MouseEntered
        cartagigante.setIcon(Carta3.getIcon());
    }//GEN-LAST:event_Carta3MouseEntered

    private void Carta3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta3MouseExited
       cartagigante.setIcon(null);
    }//GEN-LAST:event_Carta3MouseExited
    
    private void ordenarJogadores(){
        Random primeiro = new Random();
        turno = primeiro.nextInt(4);
     
       JOptionPane.showMessageDialog(null,"Primeiro a jogar é o " + jogadores.get(turno).getNome());
       rodartabuleiro();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Battle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atual;
    private javax.swing.JLabel Carta1;
    private javax.swing.JLabel Carta2;
    private javax.swing.JLabel Carta3;
    private javax.swing.JLabel Personagem1;
    private javax.swing.JLabel Personagem3;
    private javax.swing.JLabel Soco;
    private javax.swing.JLabel Vezde;
    private javax.swing.JLabel Vidaatual;
    private javax.swing.JLabel cartagigante;
    private javax.swing.JLabel contadordeturno;
    private javax.swing.JLabel fundo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel personagem2;
    private javax.swing.JLabel vida1;
    private javax.swing.JLabel vida2;
    private javax.swing.JLabel vida3;
    // End of variables declaration//GEN-END:variables
}
