/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package commanders.of.jogoddar;

import commanders.of.jogoddar.classes.Jogador;

/**
 *
 * @author natha
 */
public class gameOver extends javax.swing.JFrame {
    
    public gameOver(Jogador jogador) {
        initComponents();
        this.setResizable(false);
        vencedor.setText("O vencedor foi:"+jogador.getNome());
        classe.setText("Classe: "+jogador.getpersonagem().getnome());
        vida.setText(Integer.toString(jogador.getVida()));
        
    }

    private gameOver() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        classe = new javax.swing.JLabel();
        vida = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vencedor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(null);

        classe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        classe.setForeground(new java.awt.Color(255, 255, 255));
        classe.setText("Classe:");
        jPanel1.add(classe);
        classe.setBounds(1160, 350, 180, 40);

        vida.setForeground(new java.awt.Color(255, 255, 255));
        vida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanders/of/jogoddar/vidamaispequena.png"))); // NOI18N
        vida.setText("texto");
        vida.setToolTipText("");
        vida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        vida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(vida);
        vida.setBounds(1260, 260, 50, 60);

        jButton3.setBackground(new java.awt.Color(0, 153, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Menu Inicial");
        jButton3.setToolTipText("");
        jPanel1.add(jButton3);
        jButton3.setBounds(0, 750, 170, 110);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Fechar Jogo");
        jButton1.setToolTipText("");
        jPanel1.add(jButton1);
        jButton1.setBounds(1330, 750, 170, 110);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vida:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1180, 270, 70, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanders/of/jogoddar/trofeu.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(990, 200, 510, 470);

        vencedor.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        vencedor.setForeground(new java.awt.Color(255, 255, 255));
        vencedor.setText("Vencedor:");
        jPanel1.add(vencedor);
        vencedor.setBounds(470, 0, 490, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natha\\OneDrive\\Documentos\\Commanders of Jogoddar\\icons\\ganhador.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -50, 1500, 1010);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameOver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel classe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel vencedor;
    private javax.swing.JLabel vida;
    // End of variables declaration//GEN-END:variables
}
