/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package commanders.of.jogoddar;
import commanders.of.jogoddar.classes.Jogador;
import commanders.of.jogoddar.classes.Musica;
import commanders.of.jogoddar.classes.Personagem;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author labccet
 */
public class SelecionarPersonagem extends javax.swing.JFrame {
        private Musica selecao = new Musica("musicas\\\\selecao.wav");
        private Musica vinheta = new Musica("musicas\\\\btnvinheta.wav");
        private ArrayList<Jogador> personagenssel = new ArrayList<Jogador>();
    public SelecionarPersonagem() {
        initComponents();
        Personagem[] personagens = new Personagem[4];
        personagens[0] = Personagem.CLERIGO;
        personagens[1] = Personagem.GUERREIRO;
        personagens[2] = Personagem.MAGO;
        personagens[3] = Personagem.PALADINO;
        for(Personagem personagem : personagens){
            jComboBox1.addItem(personagem.getnome());
            jComboBox2.addItem(personagem.getnome());
            jComboBox3.addItem(personagem.getnome());
            jComboBox4.addItem(personagem.getnome());
        }
        setResizable(false);
        selecao.iniciarmusica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setLayout(null);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(1080, 530, 290, 150);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(320, 400, 290, 150);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(1100, 270, 290, 150);

        jLabel12.setText("jLabel8");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(630, 530, 130, 110);

        jLabel11.setText("jLabel8");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(630, 410, 130, 110);

        jLabel10.setText("jLabel8");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(640, 290, 130, 110);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(330, 150, 290, 150);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Player 3");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(860, 400, 110, 40);

        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(640, 170, 130, 110);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Player 4");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(860, 520, 110, 40);

        jComboBox4.setBackground(new java.awt.Color(0, 153, 204));
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(780, 440, 270, 40);

        jComboBox3.setBackground(new java.awt.Color(0, 153, 204));
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(780, 560, 270, 40);

        jComboBox2.setBackground(new java.awt.Color(0, 153, 204));
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(780, 200, 270, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Player 2");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(860, 280, 110, 40);

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("IR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(860, 650, 100, 60);

        jComboBox1.setBackground(new java.awt.Color(0, 153, 204));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(780, 320, 270, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Selecione seu Personagem");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(690, -30, 440, 100);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Player 1");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(860, 150, 100, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanders/of/jogoddar/backgroundteste.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, -270, 1890, 1260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1835, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          selecao.pararmusica();
           if(jComboBox1.getSelectedItem()=="Clerigo"){
               personagenssel.add(new Jogador("Player1",Personagem.CLERIGO));
        }
        else if(jComboBox1.getSelectedItem() == "Guerreiro"){
            personagenssel.add(new Jogador("Player1",Personagem.GUERREIRO));

        }
         else if(jComboBox1.getSelectedItem() == "Mago"){
            personagenssel.add(new Jogador("Player1",Personagem.MAGO));
         }
         else if(jComboBox1.getSelectedItem() == "Paladino"){
            personagenssel.add(new Jogador("Player1",Personagem.PALADINO));
        }
        
        if(jComboBox2.getSelectedItem()=="Clerigo"){
               personagenssel.add(new Jogador("Player2",Personagem.CLERIGO));

        }
        else if(jComboBox2.getSelectedItem() == "Guerreiro"){
            personagenssel.add(new Jogador("Player2",Personagem.GUERREIRO));

        }
         else if(jComboBox2.getSelectedItem() == "Mago"){
            personagenssel.add(new Jogador("Player2",Personagem.MAGO));

        }
         else if(jComboBox2.getSelectedItem() == "Paladino"){
            personagenssel.add(new Jogador("Player2",Personagem.MAGO));

        }
            
            
        if(jComboBox3.getSelectedItem()=="Clerigo"){
           personagenssel.add(new Jogador("Player3",Personagem.CLERIGO));

        }
        else if(jComboBox3.getSelectedItem() == "Guerreiro"){
            personagenssel.add(new Jogador("Player3",Personagem.GUERREIRO));

        }
         else if(jComboBox3.getSelectedItem() == "Mago"){
            personagenssel.add(new Jogador("Player3",Personagem.MAGO));

         }
         else if(jComboBox3.getSelectedItem() == "Paladino"){
            personagenssel.add(new Jogador("Player3",Personagem.PALADINO));

            
        }
        
            
        if(jComboBox4.getSelectedItem()=="Clerigo"){
           personagenssel.add(new Jogador("Player4",Personagem.CLERIGO));

        }
        else if(jComboBox4.getSelectedItem() == "Guerreiro"){
            personagenssel.add(new Jogador("Player4",Personagem.GUERREIRO));

        }
         else if(jComboBox4.getSelectedItem() == "Mago"){
            personagenssel.add(new Jogador("Player4",Personagem.MAGO));

         }
         else if(jComboBox4.getSelectedItem() == "Paladino"){
            personagenssel.add(new Jogador("Player4",Personagem.PALADINO));

            
        }
        dispose();
        Battle bt = new Battle(personagenssel.get(0),personagenssel.get(1),personagenssel.get(2),personagenssel.get(3));
        dispose();
        bt.setVisible(true);

          vinheta.iniciarmusica();
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:]
        if(jComboBox2.getSelectedItem()=="Clerigo"){
            ImageIcon barbaro = new ImageIcon("icons\\\\clerigo.png");
            jLabel8.setIcon(barbaro);
            jLabel9.setText("<html>-Pode curar seus aliados<br>-Healer<br>-Tem um Deus Maneiro</html>");
        }
        else if(jComboBox2.getSelectedItem() == "Guerreiro"){
            ImageIcon guerreiro = new ImageIcon("icons\\\\guerreiro.png");
            jLabel8.setIcon(guerreiro);
            jLabel9.setText("<html>-Equilibrio entre ataque e defesa<br>-Bonus com armas<br>-Adoram olhar seus musculos no espelho</html>");
        }
         else if(jComboBox2.getSelectedItem() == "Mago"){
            ImageIcon mago = new ImageIcon("icons\\\\mago.png");
            jLabel8.setIcon(mago);
            jLabel8.setText("<html>-Longa distância<br>-Bonus com mágicas<br>São nerds estudiosos</html>");
        }
         else if(jComboBox2.getSelectedItem() == "Paladino"){
            ImageIcon paladino = new ImageIcon("icons\\\\paladino.png");
            jLabel8.setIcon(paladino);
            jLabel9.setText("<html>-Classe defensiva<br>-Bonus com cartas defensivas<br>Odeia o Deus do Clérigo</html>");
        }

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         if(jComboBox1.getSelectedItem()=="Clerigo"){
            ImageIcon barbaro = new ImageIcon("icons\\\\clerigo.png");
            jLabel10.setIcon(barbaro);
            jLabel13.setText("<html>-Pode curar seus aliados<br>-Healer<br>-Tem um Deus Maneiro</html>");
        }
        else if(jComboBox1.getSelectedItem() == "Guerreiro"){
            ImageIcon guerreiro = new ImageIcon("icons\\\\guerreiro.png");
            jLabel10.setIcon(guerreiro);
            jLabel13.setText("<html>-Equilibrio entre ataque e defesa<br>-Bonus com armas<br>-Adoram olhar seus musculos no espelho</html>");
        }
         else if(jComboBox1.getSelectedItem() == "Mago"){
            ImageIcon mago = new ImageIcon("icons\\\\mago.png");
            jLabel10.setIcon(mago);
            jLabel13.setText("<html>-Longa distância<br>-Bonus com mágicas<br>São nerds estudiosos</html>");
        }
         else if(jComboBox1.getSelectedItem() == "Paladino"){
            ImageIcon paladino = new ImageIcon("icons\\\\paladino.png");
            jLabel10.setIcon(paladino);
            jLabel13.setText("<html>-Classe defensiva<br>-Bonus com cartas defensivas<br>Odeia o Deus do Clérigo</html>");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        if(jComboBox4.getSelectedItem()=="Clerigo"){
            ImageIcon barbaro = new ImageIcon("icons\\\\clerigo.png");
            jLabel11.setIcon(barbaro);
            jLabel14.setText("<html>-Pode curar seus aliados<br>-Healer<br>-Tem um Deus Maneiro</html>");
        }
        else if(jComboBox4.getSelectedItem() == "Guerreiro"){
            ImageIcon guerreiro = new ImageIcon("icons\\\\guerreiro.png");
            jLabel11.setIcon(guerreiro);
            jLabel14.setText("<html>-Equilibrio entre ataque e defesa<br>-Bonus com armas<br>-Adoram olhar seus musculos no espelho</html>");
        }
         else if(jComboBox4.getSelectedItem() == "Mago"){
            ImageIcon mago = new ImageIcon("icons\\\\mago.png");
            jLabel11.setIcon(mago);
            jLabel14.setText("<html>-Longa distância<br>-Bonus com mágicas<br>São nerds estudiosos</html>");
         }
         else if(jComboBox4.getSelectedItem() == "Paladino"){
            ImageIcon paladino = new ImageIcon("icons\\\\paladino.png");
            jLabel11.setIcon(paladino);
            jLabel14.setText("<html>-Classe defensiva<br>-Bonus com cartas defensivas<br>Odeia o Deus do Clérigo</html>");
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        if(jComboBox3.getSelectedItem()=="Clerigo"){
            ImageIcon barbaro = new ImageIcon("icons\\\\clerigo.png");
            jLabel12.setIcon(barbaro);
            jLabel15.setText("<html>-Pode curar seus aliados<br>-Healer<br>-Tem um Deus Maneiro</html>");
        }
        else if(jComboBox3.getSelectedItem() == "Guerreiro"){
            ImageIcon guerreiro = new ImageIcon("icons\\\\guerreiro.png");
            jLabel12.setIcon(guerreiro);
            jLabel15.setText("<html>-Equilibrio entre ataque e defesa<br>-Bonus com armas<br>-Adoram olhar seus musculos no espelho</html>");
        }
         else if(jComboBox3.getSelectedItem() == "Mago"){
            ImageIcon mago = new ImageIcon("icons\\\\mago.png");
            jLabel12.setIcon(mago);
            jLabel15.setText("<html>-Longa distância<br>-Bonus com mágicas<br>São nerds estudiosos</html>");
         }
         else if(jComboBox3.getSelectedItem() == "Paladino"){
            ImageIcon paladino = new ImageIcon("icons\\\\paladino.png");
            jLabel12.setIcon(paladino);
            jLabel15.setText("<html>-Classe defensiva<br>-Bonus com cartas defensivas<br>Odeia o Deus do Clérigo</html>");
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecionarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecionarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecionarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecionarPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecionarPersonagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
